steps:

  - id: "Running docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
    args: ['-f', './devops/docker/laravel/docker-compose.cloudbuild.yml', 'up', '-d']

  - id: "Running docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']